const express = require('express')
const routes = express.Router()
const UserController = require('./Users.controller')
const UserValidation = require('./Users.validation')
const validate = new UserValidation()
const user = new UserController()
const authorise = require('../../middleWare/authorise')
const auth = new authorise()
const multer = require('multer')

const upload = multer({ dest: 'uploads' })
routes.post('/signup', validate.signup,upload.single('user_img'), user.signup)
routes.post('/login', validate.login, user.login)
routes.get('/allUsers', auth.userAuth, user.getAllUsers)
module.exports = routes